name: Deploy Dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    concurrency:
      group: deploy-dev
      cancel-in-progress: true

    steps:
      - name: Dev Deploy app
        run: |
          cd /home/saher/Test/saher-frontend
          git fetch origin
          git reset --hard origin/dev

      - name: Quality gates
        run: |
          cd /home/saher/Test/saher-frontend
          corepack enable

          pnpm --version

          pnpm install --frozen-lockfile
          pnpm lint && pnpm typecheck && pnpm test

      - name: Docker Compose rebuild
        run: |
          cd /home/saher/Test/
          docker compose up -d --build frontend

      - name: Cleanup old images
        run: docker image prune -a

      - name: Verify containers
        run: docker ps

